FROM ubuntu:latest
WORKDIR /app
COPY . .
ARG REBUILD=<%= Time.now.to_i %>
<% if File.exist?('build.env') -%>
ARG <%= IO.readlines("build.env").map(&:strip).join(" ") %>
<% end -%>
RUN bin/grep_env.sh
CMD ["bash"]
