FROM ubuntu:latest
WORKDIR /app
COPY . .
# uncomment to always force rebuild
# ARG REBUILD=<%= Time.now.to_i %>
<% if File.exist?('build.env') -%>
ARG <%= IO.readlines("build.env").map { |l| l.strip.split('=').first.sub(/.*export /,'') }.join(" ") %>
<% end -%>
RUN bin/grep_env.sh
# RUN bin/wrapper.sh bin/test.sh
# RUN bin/wrapper.sh npm install
CMD ["bash"]
